apiVersion: v1
kind: Pod
metadata:
  name: cephfs
spec:
  containers:
  - name: cephfs-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/cephfs"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
      - 10.2.0.140:6789
      - 10.2.0.141:6789
      user: admin
      secretRef:
        name: AQBay6NY8YRGGhAAofyjGd5dYN2TnCIK1OzvlQ==
      readOnly: true
